### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by nickjackson** [peterthomasross/peterthomasross.github.io#4]
Hey, could you give the buttons this class, and make the first button an actual button rather than div.

I like these classes, but you will need to play around with the textbox, to give it similar padding.

``` css
.btn {
  font-family: "Proxima Nova", sans-serif;
  color: #FFF;
  display: inline-block;   
  font-size: 14px;   
  font-weight: bold;   
  text-align:center;            
  padding: 14px 40px;      
  outline:none;   
  border-radius: 2px;
  border:0;
  cursor:pointer;
  -webkit-font-smoothing: antialiased;
  background-color: #9BB43B;
}

.btn:active {
  -webkit-box-shadow: 0 2px 3px rgba(0, 0, 0, 0.3) inset;
  -moz-box-shadow: 0 2px 3px rgba(0,0,0,0.3) inset; 
  -o-box-shadow: 0 2px 3px rgba(0,0,0,0.3) inset; 
  box-shadow: 0 2px 3px rgba(0, 0, 0, 0.3) inset;
  background-color: #829929;
}

```
